### ISSUE TITLE
How can i change frontend url from 127.0.0.1 to another ip ?

### ISSUE THREAD

**Issue by natpavin** [ezaquarii/openvpn-at-home#1]
I can't change frontend url from ip : 127.0.0.1

openvpn-at-home/backend/openvpnathome/settings

ROOT_URLCONF = 'openvpnathome.urls'
WSGI_APPLICATION = 'openvpnathome.wsgi.application'
ALLOWED_HOSTS = ['*']
INTERNAL_IPS = ['127.0.0.1'] >> change to other ip

**Comment by ezaquarii** [comment]
Try putting that in settings.py:

```
try:
    from openvpnathome.config import ALLOWED_HOSTS
except:
    ALLOWED_HOSTS = ['*']

try:
    from openvpnathome.config import INTERNAL_IPS
except:
    INTERNAL_IPS = ['127.0.0.1']
```
This will import setting from your private config file and fallback to default value, if not configured provided.

I don't have time to test it now, but if you verify this, I'd accept the patch.

**Comment by natpavin** [comment]
I try to edit as your suggestion, but config isn't replace follow setting.py. It always show 127.0.0.1:8001.

**Comment by ezaquarii** [comment]
The address you are referring to is server binding address. This is not configured via settings.

ALLOWED_HOSTS is a list of strings representing the host/domain names that this Django site can serve. This is a security measure to prevent HTTP Host header attacks, which are possible even under many seemingly-safe web server configurations.

INTERNAL_IPS 
A list of IP addresses, as strings, that:
Allow the debug() context processor to add some variables to the template context.
Can use the admindocs bookmarklets even if not logged in as a staff user.
Are marked as “internal” (as opposed to “EXTERNAL”) in AdminEmailHandler emails.

**Comment by ezaquarii** [comment]
To bind the server to a different address, you can just run `./manage.py runserver` manually.

**Comment by natpavin** [comment]
Ok guy, I have finish run follow

cd openvpn-at-home/backend/
./manage.py runserver my_ip:8001

before Run above command I have install 

Python : 3.6.4

pip install django (version 2.0.2)
pip install django-picklefield
pip install django-constance
pip install django-debug-toolbar
pip install djangorestframework
pip install django-x509

**Comment by ezaquarii** [comment]
You're not supposed to install dependencies manually. Please do it with `make devel`

**Comment by natpavin** [comment]
I have deploy as make devel but manual step can't to use "./mange.py runserver my_ip, If I try to run I just manual install.

**Comment by ezaquarii** [comment]
This setup uses Python virtualenv. You must import the virtualenv before using manage.py.

Please try in your shell:
source backend/env/bin/activate

That will import the virtualenv and manage.py should work.

**Comment by ezaquarii** [comment]
Please familiarize yourself with https://pypi.python.org/pypi/virtualenv

**Comment by natpavin** [comment]
That’s great.
