### ISSUE TITLE
E-mail backend should be dynamically configurable

### ISSUE THREAD

**Issue by ezaquarii** [ezaquarii/openvpn-at-home#12]
Currently, the e-mail backend must be configured vie settings.json due to limitations of Django settings.
Create new e-mail backend to read configuration from a database entry.

**Comment by Skchoudhary** [comment]
Hi @ezaquarii, I would like to work on this issue, But can explain bit more about the issue.

**Comment by ezaquarii** [comment]
This is too troublesome. E-mail will be configured in settings.json only.
