### ISSUE TITLE
Remove dynamic e-mail configuration form and settings model

### ISSUE THREAD

**Issue by ezaquarii** [ezaquarii/openvpn-at-home#19]

**Comment by jebruen** [comment]
Hi, could you elaborate on this enhancement(where it is, etc)? I would like to contribute.

**Comment by ezaquarii** [comment]
Frontend: Settings panel contains SMTP configuration.
Backend: SettingsModel, configure management script and custom e-mail backend.

I simply see no point in having a configuration in 2 places. Django e-mail backend uses settings.json.
