### ISSUE TITLE
Use a published version of django-x509

### ISSUE THREAD

**Issue by r-darwish** [ezaquarii/openvpn-at-home#5]
I'm trying to create a Docker container for the application based on Alpine Linux. My problem is that the application depends on a bundled wheel that may not suite Alpine Linux. Is it possible to use a published version of django-x509, such as 0.4?

**Comment by ezaquarii** [comment]
I bundled the wheel as the officially published version missed some features at the time. I guess that with the recent release of django-x509 I don't need it anymore.

BTW, why it doesn't suite Alpine?

**Comment by ezaquarii** [comment]
You can now use version 0.4.

At a cost of broken database migrations. You need to bootstrap the database again. This is an issue with SQLite that I'll be reporting to Django project.

**Comment by r-darwish** [comment]
Thanks!

**Comment by ezaquarii** [comment]
Don't forget to open a PR! :)
I'm keen on packaging it into a docker container, but I had no time to do it.

**Comment by r-darwish** [comment]
Sure. Do you mind if I change the location of the database into a sub-directory inside the root directory? Because in a Docker container the database will have to exists in a directory which is defined as a volume.

**Comment by ezaquarii** [comment]
Database is configured using a config.py file. You can set your db location to whatever you want.

You might want to extend management command `configure` a bit to supply your own config template.|
In case of docker, it wouldn't hurt if you hardcode db location as an absolute path.

**Comment by ezaquarii** [comment]
Check new version. You can now supply your own config template to `./manage.py configure`.
